site_name: DevOps/SRE Task Management
site_description: Personal documentation for DevOps/SRE tasks, planning, and infrastructure management

nav:
  - Home: index.md
  - Planning:
    - Overview: planning/index.md
    - Security Hardening: planning/security-hardening.md
    - Post-Incident Response (Ransomware): planning/post-incident.md
    - Ceph Memory Limit Fix: planning/ceph-memory-limit-fix.md
    - Monitoring Kubernetes Phase 1: planning/monitoring-kubernetes.md
    - Monitoring Kubernetes Phase 2: planning/monitoring-kubernetes-phase2.md
  - Monitoring Matrix: monitoring-matrix.md
  - Infrastructure: infrastructure.md
  - Runbooks: runbooks.md

theme:
  name: windmill
  custom_dir: docs/
  
extra_css:
  - css/custom.css

plugins:
  - search
  - mermaid2

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - toc:
      permalink: true

